package com.spark.falcon.cashmanagement.entity;

public enum CashMovementType {
    CASH_SALE,
    CUSTOMER_DUE_COLLECTION,
    SUPPLIER_REFUND_RECEIVED,
    OPERATING_EXPENSE_PAYMENT,
    SUPPLIER_DUE_PAYMENT,
    CUSTOMER_REFUND,
    RECOVERABLE_DEPOSIT_ADVANCE,
    RECOVERABLE_AMOUNT_RECEIVED,
    DEPOSIT,
    WITHDRAWAL,
    CASH_DROP,
    HANDOVER,
    BANK_DEPOSIT,
    BANK_WITHDRAWAL,
    VARIANCE_ADJUSTMENT,
    OPENING_FLOAT,
    REVERSAL
}
