package com.spark.falcon.sale.entity;

public enum SaleAuditAction {
    SALE_DRAFT_CREATED,
    SALE_DRAFT_UPDATED,
    SALE_HELD,
    SALE_INVENTORY_POSTED,
    SALE_CONFIRMED,
    CUSTOMER_PAYMENT_APPLIED,
    CUSTOMER_PAYMENT_REVERSED,
    SALE_RETURN_DRAFT_CREATED,
    SALE_RETURN_CONFIRMED,
    SALE_RETURN_REVERSED,
    SALE_VOIDED,
    SALE_REVERSED
}
