package com.spark.falcon.inventory.entity;
import jakarta.persistence.*;import lombok.*;import java.time.*;import java.util.*;
@Entity @Table(name="physical_stock_counts",uniqueConstraints=@UniqueConstraint(name="uk_stock_count_business_key",columnNames={"business_id","idempotency_key"})) @Getter @NoArgsConstructor
public class PhysicalStockCount {
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Long id;@Column(name="business_id",nullable=false)private Long businessId;@Column(name="branch_id",nullable=false)private Long branchId;@Column(name="count_date",nullable=false)private LocalDate countDate;@Enumerated(EnumType.STRING)@Column(nullable=false,length=30)private StockCountScope scope;@Column(name="assigned_counter_id",nullable=false)private Long assignedCounterId;@Column(length=1000)private String notes;@Column(name="attachment_reference",length=500)private String attachmentReference;@Enumerated(EnumType.STRING)@Column(nullable=false,length=30)private InventoryOperationStatus status;@Column(name="created_by",nullable=false)private Long createdBy;@Column(name="approved_by")private Long approvedBy;@Column(name="created_at",nullable=false)private Instant createdAt;@Column(name="submitted_at")private Instant submittedAt;@Column(name="approved_at")private Instant approvedAt;@Column(name="posted_at")private Instant postedAt;@Column(name="idempotency_key",nullable=false,length=100)private String idempotencyKey;
 @OneToMany(mappedBy="count",cascade=CascadeType.ALL,orphanRemoval=true)private List<PhysicalStockCountRow> rows=new ArrayList<>();
 public static PhysicalStockCount create(Long b,Long branch,LocalDate date,StockCountScope scope,Long assigned,String notes,String attachment,Long actor,String key,Instant now){PhysicalStockCount c=new PhysicalStockCount();c.businessId=b;c.branchId=branch;c.countDate=date;c.scope=scope;c.assignedCounterId=assigned;c.notes=notes;c.attachmentReference=attachment;c.createdBy=actor;c.idempotencyKey=key;c.status=InventoryOperationStatus.DRAFT;c.createdAt=now;return c;}
 public void addRow(PhysicalStockCountRow r){if(status!=InventoryOperationStatus.DRAFT)throw new IllegalStateException("Only Draft count can change rows");r.attach(this);rows.add(r);} public void updateDraft(LocalDate date,StockCountScope scope,Long assigned,String notes,String attachment){require(InventoryOperationStatus.DRAFT);countDate=Objects.requireNonNull(date,"countDate is required");this.scope=Objects.requireNonNull(scope,"scope is required");assignedCounterId=Objects.requireNonNull(assigned,"assignedCounterId is required");this.notes=notes;attachmentReference=attachment;} public void clearDraftRows(){require(InventoryOperationStatus.DRAFT);rows.clear();} public void start(){require(InventoryOperationStatus.DRAFT);status=InventoryOperationStatus.COUNTING;}public void submit(Instant n){if(status!=InventoryOperationStatus.DRAFT&&status!=InventoryOperationStatus.COUNTING)throw new IllegalStateException("Only Draft or Counting count can be submitted");status=InventoryOperationStatus.SUBMITTED;submittedAt=n;}public void review(){require(InventoryOperationStatus.SUBMITTED);status=InventoryOperationStatus.UNDER_REVIEW;}public void approve(Long a,Instant n){if(status!=InventoryOperationStatus.SUBMITTED&&status!=InventoryOperationStatus.UNDER_REVIEW)throw new IllegalStateException("Count is not reviewable");status=InventoryOperationStatus.APPROVED;approvedBy=a;approvedAt=n;}public void reject(){if(status!=InventoryOperationStatus.SUBMITTED&&status!=InventoryOperationStatus.UNDER_REVIEW)throw new IllegalStateException("Count is not reviewable");status=InventoryOperationStatus.REJECTED;}public void cancel(){if(status!=InventoryOperationStatus.DRAFT&&status!=InventoryOperationStatus.COUNTING)throw new IllegalStateException("Count cannot be cancelled");status=InventoryOperationStatus.CANCELLED;}public void posted(Instant n){require(InventoryOperationStatus.APPROVED);status=InventoryOperationStatus.POSTED;postedAt=n;}private void require(InventoryOperationStatus s){if(status!=s)throw new IllegalStateException("Count must be "+s);}
 public void requestRecount(){require(InventoryOperationStatus.UNDER_REVIEW);status=InventoryOperationStatus.COUNTING;}
}
