package com.spark.falcon.product.entity.enumtype;

public enum ProductAuditAction {
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_STATUS_CHANGED,
    PRODUCT_ARCHIVED,
    PRODUCT_RESTORED,
    EXPIRY_TRACKING_DISABLED,
    VARIANT_CREATED,
    VARIANT_UPDATED,
    VARIANT_STATUS_CHANGED,
    BARCODE_CREATED,
    BARCODE_DEACTIVATED,
    UNIT_CONVERSION_CREATED,
    UNIT_CONVERSION_DEACTIVATED
}
