package com.spark.falcon.purchase.entity.enumtype;

public enum PurchaseAuditAction {
    PURCHASE_DRAFT_CREATED,
    PURCHASE_DRAFT_UPDATED,
    PURCHASE_DRAFT_DELETED,
    PURCHASE_CONFIRMED,
    SUPPLIER_PAYMENT_POSTED,
    SUPPLIER_PAYMENT_REVERSED,
    PURCHASE_RETURN_DRAFT_CREATED,
    PURCHASE_RETURN_DRAFT_UPDATED,
    PURCHASE_RETURN_DRAFT_DELETED,
    PURCHASE_RETURN_CONFIRMED,
    STOCK_IMPORT_UPLOADED,
    STOCK_IMPORT_VALIDATED,
    STOCK_IMPORT_POSTED,
    STOCK_IMPORT_REVERSED
}
