package com.spark.falcon.settings.entity.enumtype;

public enum SettingsAuditAction {
    BRANCH_OPERATIONAL_SETTINGS_UPDATED,
    PAYMENT_METHOD_CREATED,
    PAYMENT_METHOD_UPDATED,
    PAYMENT_METHOD_STATUS_CHANGED,
    PAYMENT_METHOD_ARCHIVED,
    UNIT_CREATED,
    UNIT_UPDATED,
    UNIT_STATUS_CHANGED,
    UNIT_ARCHIVED,
    TAX_RATE_CREATED,
    TAX_RATE_UPDATED,
    TAX_RATE_STATUS_CHANGED,
    TAX_RATE_ARCHIVED,
    PRINTER_CREATED,
    PRINTER_UPDATED,
    PRINTER_STATUS_CHANGED,
    PRINTER_ARCHIVED,
    PRINTER_TESTED
}
